<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "article".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $content
 * @property string $image
 * @property integer $viewed
 * @property integer $user_id
 * @property integer $cate_id
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 */
class Article extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'description', 'content', 'cate_id'], 'required'],
            [['description', 'content'], 'string'],
            [['viewed', 'user_id', 'cate_id', 'created_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['created_at', 'updated_at'], 'date','format'=>'php:Y-m-d'],
            [['title'], 'string', 'max' => 150],
            [['image'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'content' => 'Content',
            'image' => 'Image',
            'viewed' => 'Viewed',
            'user_id' => 'User ID',
            'cate_id' => 'Cate ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
        ];
    }
    public function saveImage($filename){
        $this->image=$filename;
        return $this->save(false);
    }
    public function deleteImage(){
        $imageUploadModel=new ImageUpload();
        $imageUploadModel->deleteCurrentimage($this->image);
    }
    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
    public  function  getImage(){
        return ($this->image)?'/uploads/'.$this->image:'/no-image.png';
    }
}
